runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app -t 600

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.app

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"

resources:
  memory_gb: 4
